"""Initial migration

Revision ID: 26560bdb910f
Revises: 
Create Date: 2024-02-27 20:35:52.937083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26560bdb910f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('instructions', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('image', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('last_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.add_column('articles_history', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles_history', 'admins', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles_history', type_='foreignkey')
    op.drop_column('articles_history', 'admin_id')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_column('articles', 'last_date')
    op.drop_column('articles', 'image')
    op.drop_column('articles', 'instructions')
    op.drop_column('articles', 'title')
    # ### end Alembic commands ###
