"""Ajout de is_temporary dans Article

Revision ID: 87479f3ba491
Revises: 99f544b0d5ca
Create Date: 2024-02-28 16:28:17.693520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87479f3ba491'
down_revision: Union[str, None] = '99f544b0d5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_temporary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'is_temporary')
    # ### end Alembic commands ###
