"""Ajout de previous_instructions dans ArticleHistory

Revision ID: 99f544b0d5ca
Revises: 26560bdb910f
Create Date: 2024-02-28 10:45:32.204185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f544b0d5ca'
down_revision: Union[str, None] = '26560bdb910f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles_history', sa.Column('previous_instructions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles_history', 'previous_instructions')
    # ### end Alembic commands ###
